# Generated by Django 4.1.1 on 2022-10-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_historicalproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical category', 'verbose_name_plural': 'historical Categories'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Product (Platillo)', 'verbose_name_plural': 'historical Products (Platillos)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product (Platillo)', 'verbose_name_plural': 'Products (Platillos)'},
        ),
    ]
