# Generated by Django 4.1.1 on 2022-10-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='state',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='historicalcategory',
            old_name='state',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='state',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='state',
            new_name='is_active',
        ),
    ]
