# Generated by Django 4.1.1 on 2022-10-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_state_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
