# Generated by Django 4.1.1 on 2022-10-22 22:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='is_active',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='state',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 17, 37, 1, 272975), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='deleted_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 17, 37, 7, 833275), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='modified_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 22, 17, 37, 14, 649246), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
