# Generated by Django 4.1.1 on 2022-10-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_active_historicaluser_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='state',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='state',
            new_name='is_active',
        ),
    ]
