# Generated by Django 4.1.1 on 2022-10-24 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('has_delivery', models.BooleanField(default=False)),
                ('social_medias', models.CharField(blank=True, choices=[('WA', 'Whatsapp'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('IG', 'Instagram')], max_length=2, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/localfood/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='images/localfood/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local Food (Negocio)',
                'verbose_name_plural': 'Local Foods (Negocios)',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLocalFood',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, editable=False)),
                ('modified_at', models.DateField(blank=True, editable=False)),
                ('deleted_at', models.DateField(blank=True, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('has_delivery', models.BooleanField(default=False)),
                ('social_medias', models.CharField(blank=True, choices=[('WA', 'Whatsapp'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('IG', 'Instagram')], max_length=2, null=True)),
                ('profile_image', models.TextField(blank=True, max_length=100, null=True)),
                ('banner_image', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Local Food (Negocio)',
                'verbose_name_plural': 'historical Local Foods (Negocios)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
