# Generated by Django 4.1.1 on 2023-01-16 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('has_delivery', models.BooleanField(default=False)),
                ('social_media', models.JSONField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/localfood/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='images/localfood/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local Food (Negocio)',
                'verbose_name_plural': 'Local Foods (Negocios)',
            },
        ),
    ]
