# Generated by Django 4.1.1 on 2022-10-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localfood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocalfood',
            name='social_medias',
        ),
        migrations.RemoveField(
            model_name='localfood',
            name='social_medias',
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='social_media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localfood',
            name='social_media',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
