# Generated by Django 4.1.1 on 2023-03-17 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localfood', '0002_alter_localfood_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfood',
            name='favs',
            field=models.ManyToManyField(related_name='favs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localfood',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
