# Generated by Django 4.1.1 on 2022-10-18 02:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('localfood', '0002_historicallocalfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocalfood',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='localfood',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 17, 21, 11, 53, 598914), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='deleted_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 17, 21, 12, 5, 654955), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='modified_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 10, 17, 21, 12, 12, 47333), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='localfood',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localfood',
            name='deleted_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='localfood',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='localfood',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicallocalfood',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='localfood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
