# Generated by Django 4.1.1 on 2022-10-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localfood', '0003_remove_historicallocalfood_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocalfood',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localfood',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
