# Generated by Django 4.1.1 on 2023-04-15 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localfood', '0003_localfood_favs_alter_localfood_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfood',
            name='favs',
            field=models.ManyToManyField(blank=True, related_name='favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
