# Generated by Django 4.1.1 on 2022-10-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localfood', '0004_alter_historicallocalfood_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallocalfood',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Local Food (Negocio)', 'verbose_name_plural': 'historical Local Foods (Negocios)'},
        ),
        migrations.AlterModelOptions(
            name='localfood',
            options={'verbose_name': 'Local Food (Negocio)', 'verbose_name_plural': 'Local Foods (Negocios)'},
        ),
    ]
