# Generated by Django 4.1.1 on 2022-10-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localfood', '0005_alter_historicallocalfood_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallocalfood',
            old_name='state',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='localfood',
            old_name='state',
            new_name='is_active',
        ),
    ]
