# Generated by Django 4.1.1 on 2022-10-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localfood', '0006_rename_state_historicallocalfood_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocalfood',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='banner_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='has_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='profile_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallocalfood',
            name='social_medias',
            field=models.CharField(blank=True, choices=[('WA', 'Whatsapp'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('IG', 'Instagram')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='localfood',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='localfood',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/localfood/'),
        ),
        migrations.AddField(
            model_name='localfood',
            name='has_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localfood',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='localfood',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/localfood/'),
        ),
        migrations.AddField(
            model_name='localfood',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='localfood',
            name='social_medias',
            field=models.CharField(blank=True, choices=[('WA', 'Whatsapp'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('IG', 'Instagram')], max_length=2, null=True),
        ),
    ]
